
import utilitarios.data;
import cadastros.*;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author hanunjunior
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    data mostraData;
    String seta_look="javax.swing.plaf.metal.MetalLookAndFeel";
    
    
    
    public TelaPrincipal() {
        // Colocando a tela em fullscreen
        this.setExtendedState(MAXIMIZED_BOTH);
        initComponents();
        mostraData = new data();
        mostraData.le_data();
        lblData.setText(mostraData.dia_semana + " Feira Dia " + mostraData.dia +
                " de " + mostraData.mes + " de " + mostraData.ano);
        //mostraData.le_hora();
        //lblHora.setText("Hora atual " + mostraData.hora);
        timer1.start();
        lookandfeel();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        timer1 = new org.netbeans.examples.lib.timerbean.Timer();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblData = new javax.swing.JLabel();
        lblHora = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuCadastro = new javax.swing.JMenu();
        menuAssociados = new javax.swing.JMenuItem();
        menuCadFuncionarios = new javax.swing.JMenuItem();
        menuCadFornecedores = new javax.swing.JMenuItem();
        menuControleEstoque = new javax.swing.JMenuItem();
        menuContasReceber = new javax.swing.JMenuItem();
        menuContasPagar = new javax.swing.JMenuItem();
        menuFecharCaixa = new javax.swing.JMenuItem();
        menuMensalidades = new javax.swing.JMenuItem();
        menuMovimentoCaixa = new javax.swing.JMenuItem();
        menuPacoteCobranca = new javax.swing.JMenuItem();
        menuRegistroObituos = new javax.swing.JMenuItem();
        menuConsultas = new javax.swing.JMenu();
        menuConsAssociados = new javax.swing.JMenuItem();
        menuConsRegistroObitos = new javax.swing.JMenuItem();
        menuConsMensalidades = new javax.swing.JMenuItem();
        menuConsContasReceber = new javax.swing.JMenuItem();
        menuConsContasPagar = new javax.swing.JMenuItem();
        menuConsPacotesCobrancas = new javax.swing.JMenuItem();
        menuConsControleEstoque = new javax.swing.JMenuItem();
        menuConsMovimentoCaixa = new javax.swing.JMenuItem();
        menuCadFuncioanrios = new javax.swing.JMenuItem();
        menuRelatorios = new javax.swing.JMenu();
        menuRelAssociados = new javax.swing.JMenuItem();
        menuRelMovimentoCaixa = new javax.swing.JMenuItem();
        menuRelRegistroObitos = new javax.swing.JMenuItem();
        menuTaxaBoleto = new javax.swing.JMenuItem();
        menuRelControleEstoque = new javax.swing.JMenuItem();
        menuRelPacotesCobrancas = new javax.swing.JMenuItem();
        menuUtilitarios = new javax.swing.JMenu();
        menuWindows = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        menuSair = new javax.swing.JMenu();

        timer1.addTimerListener(new org.netbeans.examples.lib.timerbean.TimerListener() {
            public void onTime(java.awt.event.ActionEvent evt) {
                timer1OnTime(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema Gerenciador de Estoque");

        jPanel1.setBackground(new java.awt.Color(157, 147, 147));

        jButton1.setText("Associados");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jLabel1.setText("Sistema Desenvolvido por Sisdeve - Sistema em Desenvolvimento");

        jLabel2.setText("Email.: contato@sisdeve.com.br");

        jLabel3.setText(" Site.: http://www.sisdeve.com.br");

        lblData.setText("Data.:");

        lblHora.setText("Hora.:");

        jLabel4.setText("Contatos.: (062) 3371 - 4417 ou (062) 8464-3128");

        jLabel5.setIcon(new javax.swing.ImageIcon("/var/www/java/SistemaGerenciadorPax/imagem/logo.png")); // NOI18N

        menuCadastro.setMnemonic('C');
        menuCadastro.setText("Cadastros");

        menuAssociados.setText("Associados");
        menuAssociados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAssociadosActionPerformed(evt);
            }
        });
        menuCadastro.add(menuAssociados);

        menuCadFuncionarios.setText("Cadastro Funcionarios");
        menuCadFuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadFuncionariosActionPerformed(evt);
            }
        });
        menuCadastro.add(menuCadFuncionarios);

        menuCadFornecedores.setText("Cadastro Fornecedores");
        menuCadFornecedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadFornecedoresActionPerformed(evt);
            }
        });
        menuCadastro.add(menuCadFornecedores);

        menuControleEstoque.setText("Controle Estoque");
        menuControleEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuControleEstoqueActionPerformed(evt);
            }
        });
        menuCadastro.add(menuControleEstoque);

        menuContasReceber.setText("Contas a Receber");
        menuContasReceber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuContasReceberActionPerformed(evt);
            }
        });
        menuCadastro.add(menuContasReceber);

        menuContasPagar.setText("Contas a Pagar");
        menuCadastro.add(menuContasPagar);

        menuFecharCaixa.setText("Fechar Caixa");
        menuFecharCaixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuFecharCaixaActionPerformed(evt);
            }
        });
        menuCadastro.add(menuFecharCaixa);

        menuMensalidades.setText("Mensalidade");
        menuMensalidades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuMensalidadesActionPerformed(evt);
            }
        });
        menuCadastro.add(menuMensalidades);

        menuMovimentoCaixa.setText("Movimento Caixa");
        menuMovimentoCaixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuMovimentoCaixaActionPerformed(evt);
            }
        });
        menuCadastro.add(menuMovimentoCaixa);

        menuPacoteCobranca.setText("Pacotes Cobrança");
        menuPacoteCobranca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPacoteCobrancaActionPerformed(evt);
            }
        });
        menuCadastro.add(menuPacoteCobranca);

        menuRegistroObituos.setText("Registro Obitos");
        menuRegistroObituos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuRegistroObituosActionPerformed(evt);
            }
        });
        menuCadastro.add(menuRegistroObituos);

        jMenuBar1.add(menuCadastro);

        menuConsultas.setMnemonic('n');
        menuConsultas.setText("Consultas");

        menuConsAssociados.setText("Associados");
        menuConsultas.add(menuConsAssociados);

        menuConsRegistroObitos.setText("Registro Obitos");
        menuConsultas.add(menuConsRegistroObitos);

        menuConsMensalidades.setText("Mensalidades");
        menuConsultas.add(menuConsMensalidades);

        menuConsContasReceber.setText("Contas a Receber");
        menuConsultas.add(menuConsContasReceber);

        menuConsContasPagar.setText("Contas a Pagar");
        menuConsultas.add(menuConsContasPagar);

        menuConsPacotesCobrancas.setText("Pacotes Cobranças");
        menuConsultas.add(menuConsPacotesCobrancas);

        menuConsControleEstoque.setText("Controle Estoque");
        menuConsultas.add(menuConsControleEstoque);

        menuConsMovimentoCaixa.setText("Movimento Caixa");
        menuConsultas.add(menuConsMovimentoCaixa);

        menuCadFuncioanrios.setText("Funcionarios");
        menuConsultas.add(menuCadFuncioanrios);

        jMenuBar1.add(menuConsultas);

        menuRelatorios.setMnemonic('R');
        menuRelatorios.setText("Relatórios");

        menuRelAssociados.setText("Associados");
        menuRelatorios.add(menuRelAssociados);

        menuRelMovimentoCaixa.setText("Movimento Caixa");
        menuRelatorios.add(menuRelMovimentoCaixa);

        menuRelRegistroObitos.setText("Registro Obitos");
        menuRelatorios.add(menuRelRegistroObitos);

        menuTaxaBoleto.setText("Taxas - Boletos");
        menuRelatorios.add(menuTaxaBoleto);

        menuRelControleEstoque.setText("Controle Estoque");
        menuRelatorios.add(menuRelControleEstoque);

        menuRelPacotesCobrancas.setText("Pacotes Cobranças");
        menuRelatorios.add(menuRelPacotesCobrancas);

        jMenuBar1.add(menuRelatorios);

        menuUtilitarios.setMnemonic('U');
        menuUtilitarios.setText("Utilitarios");

        menuWindows.setText(" Look And Feel - Windows");
        menuWindows.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuWindowsActionPerformed(evt);
            }
        });
        menuUtilitarios.add(menuWindows);

        jMenuItem1.setText(" Look And Feel - Liquid");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        menuUtilitarios.add(jMenuItem1);

        jMenuBar1.add(menuUtilitarios);

        menuSair.setMnemonic('S');
        menuSair.setText("Sair");
        menuSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuSairMouseClicked(evt);
            }
        });
        menuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSairActionPerformed(evt);
            }
        });
        jMenuBar1.add(menuSair);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblData)
                        .addGap(252, 252, 252)
                        .addComponent(lblHora))
                    .addComponent(jLabel4)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(228, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 201, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(9, 9, 9)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblData)
                    .addComponent(lblHora))
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void timer1OnTime(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timer1OnTime
        mostraData.le_hora();
        lblHora.setText("Hora atual " + mostraData.hora);
    }//GEN-LAST:event_timer1OnTime

    private void menuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSairActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuSairActionPerformed

    private void menuSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuSairMouseClicked
        System.exit(0);
    }//GEN-LAST:event_menuSairMouseClicked

    private void menuAssociadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAssociadosActionPerformed
        new CadAssociados().show();
    }//GEN-LAST:event_menuAssociadosActionPerformed

    private void menuCadFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadFuncionariosActionPerformed
        // Funcionario
    }//GEN-LAST:event_menuCadFuncionariosActionPerformed

    private void menuCadFornecedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadFornecedoresActionPerformed
        new cadFornecedor().show();
    }//GEN-LAST:event_menuCadFornecedoresActionPerformed

    private void menuControleEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuControleEstoqueActionPerformed
        new CadProdutos().show();
    }//GEN-LAST:event_menuControleEstoqueActionPerformed

    private void menuContasReceberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuContasReceberActionPerformed
        new CadContasReceber().show();
    }//GEN-LAST:event_menuContasReceberActionPerformed

    private void menuFecharCaixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuFecharCaixaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuFecharCaixaActionPerformed

    private void menuMensalidadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuMensalidadesActionPerformed
        new CadMensalidades().show();
    }//GEN-LAST:event_menuMensalidadesActionPerformed

    private void menuMovimentoCaixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuMovimentoCaixaActionPerformed
        new CadMovimentoCaixa().show();
    }//GEN-LAST:event_menuMovimentoCaixaActionPerformed

    private void menuPacoteCobrancaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPacoteCobrancaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuPacoteCobrancaActionPerformed

    private void menuRegistroObituosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuRegistroObituosActionPerformed
        new CadObitos().show();
    }//GEN-LAST:event_menuRegistroObituosActionPerformed

    private void menuWindowsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuWindowsActionPerformed
        seta_look="com.sun.java.swing.plaf.windows.WindowsLookAndFeel";
        lookandfeel();
    }//GEN-LAST:event_menuWindowsActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        seta_look="com.birosoft.liquid.LiquidLookAndFeel";
        lookandfeel();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new CadAssociados().show();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblData;
    private javax.swing.JLabel lblHora;
    private javax.swing.JMenuItem menuAssociados;
    private javax.swing.JMenuItem menuCadFornecedores;
    private javax.swing.JMenuItem menuCadFuncioanrios;
    private javax.swing.JMenuItem menuCadFuncionarios;
    private javax.swing.JMenu menuCadastro;
    private javax.swing.JMenuItem menuConsAssociados;
    private javax.swing.JMenuItem menuConsContasPagar;
    private javax.swing.JMenuItem menuConsContasReceber;
    private javax.swing.JMenuItem menuConsControleEstoque;
    private javax.swing.JMenuItem menuConsMensalidades;
    private javax.swing.JMenuItem menuConsMovimentoCaixa;
    private javax.swing.JMenuItem menuConsPacotesCobrancas;
    private javax.swing.JMenuItem menuConsRegistroObitos;
    private javax.swing.JMenu menuConsultas;
    private javax.swing.JMenuItem menuContasPagar;
    private javax.swing.JMenuItem menuContasReceber;
    private javax.swing.JMenuItem menuControleEstoque;
    private javax.swing.JMenuItem menuFecharCaixa;
    private javax.swing.JMenuItem menuMensalidades;
    private javax.swing.JMenuItem menuMovimentoCaixa;
    private javax.swing.JMenuItem menuPacoteCobranca;
    private javax.swing.JMenuItem menuRegistroObituos;
    private javax.swing.JMenuItem menuRelAssociados;
    private javax.swing.JMenuItem menuRelControleEstoque;
    private javax.swing.JMenuItem menuRelMovimentoCaixa;
    private javax.swing.JMenuItem menuRelPacotesCobrancas;
    private javax.swing.JMenuItem menuRelRegistroObitos;
    private javax.swing.JMenu menuRelatorios;
    private javax.swing.JMenu menuSair;
    private javax.swing.JMenuItem menuTaxaBoleto;
    private javax.swing.JMenu menuUtilitarios;
    private javax.swing.JMenuItem menuWindows;
    private org.netbeans.examples.lib.timerbean.Timer timer1;
    // End of variables declaration//GEN-END:variables
    
    public void lookandfeel()
    {
         try
        {
            UIManager.setLookAndFeel(seta_look);
            SwingUtilities.updateComponentTreeUI(this);
        }
        catch(Exception erro) 
        {
           JOptionPane.showMessageDialog(null,erro);
        }
    }
}
